[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
thera_sol = "AoRNpekD8CuunokmyWvqNyXqW8PProGtQK4WFPgq8DRh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-devnet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/thera-sol-devnet.ts"
